### ISSUE TITLE
Source for Parts

### ISSUE THREAD

**Issue by misteraddons** [mackieks/Shinobi-Scaler#2]
First off, very nice work! Looks like a tidy, tiny little package. Is there a known source for the TV5725? I assume your note to mean you have to remove them from an existing GBS8200.

Cheers!

**Comment by mackieks** [comment]
Hi! I haven't seen TV5725s for sale on B2C sites like AliExpress or eBay. But you might be able to source them directly from suppliers on [Taobao](https://www.taobao.com/list/item/wap/541019911390.htm)  or [Alibaba](https://m.alibaba.com/product/1600531035318/PLC-for-TV5725-quote-by-letter.html). (I recommend SuperBuy for Taobao proxying.)

**Comment by misteraddons** [comment]
Thanks!
