### ISSUE TITLE
The output is rgbhv

### ISSUE THREAD

**Issue by ZeFoxii** [mackieks/Shinobi-Scaler#3]
I have two questions, first what is the pcb you used to get the rgbhv to the lcd screen in your pictures?

Second let's say I build this and want to just make a mini gbs-c what would be the best way to get it to hdmi?

How hard would it be to add a ms9288a to hdmi connector to the rgbhv output. I'm new to this kinda thing so I'm asking.

**Comment by ZeFoxii** [comment]
Do you think I could use a wii to hdmi adapter with a ms988a?

**Comment by mackieks** [comment]
Hi! The LCD in the photos is a ZJ050NA-08C with a generic VGA driver board. Widely available on AliExpress, eBay, etc. Just search for that model number.

You can certainly add a VGA-to-HDMI converter if you'd like. There are a couple blog posts/tutorials floating around showing how to wire one up to a GBS-8200. They usually only need 5V, GND, and RGBHV. 

Wii2HDMI adapters use YPbPr, not VGA, and while GBS-Control has an experimental YPbPr output feature, I haven't tested it and can't speak to its stability or compatibility.

**Comment by ZeFoxii** [comment]
I have one last question when programming did you use the official GBSC settings or the settings provided by your picture?

The reason I ask is because my plan is to use the settings in your picture and I just want to be sure when I hit the red button things go well.

**Comment by mackieks** [comment]
If you're building a Shinobi Scaler, you need to use the settings shown in the README.
