### ISSUE TITLE
YPBPR Output

### ISSUE THREAD

**Issue by ZeFoxii** [mackieks/Shinobi-Scaler#4]
You stated in the read me

240p/480i RGBs input; 480p/720p/960p/1080p RGBHV/VGA/"YPbPr" output

How do I enable this output from the shinobi scaler?

**Comment by ZeFoxii** [comment]
And once enabled what pins would I be soldering.

**Comment by ZeFoxii** [comment]
My personal guess was just connect it to RGB and G would somehow through software start transmitting Y from the GBS-control software. But I don't know that as

A. I haven't built my shinobi scaler yet. 

B. I don't want to damage hardware so I thought I'd ask.

**Comment by ZeFoxii** [comment]
I really love your project btw, so I apologize if I come off as rude.

**Comment by mackieks** [comment]
Hello again! I'm glad you like the project. Like I said in #3, I haven't tested the YPbPr output myself. It's an experimental mode and compatibility with displays may be hit or miss.

But theoretically you just need to enable the "RGBHV/Component" toggle in the Settings menu.
![image](https://github.com/mackieks/Shinobi-Scaler/assets/49252894/e9b34912-c913-4614-abdb-ea6e29045672)

Wiring should match the colors of YPbPr cables. So **R→Pr**, **B→Pb**, and **G→Y**. 
![image](https://github.com/mackieks/Shinobi-Scaler/assets/49252894/27280dba-2de1-4529-a06b-f6c42e6281c5)

Sync is embedded in the Y channel with component video, so you don't need to wire H or V.

**Comment by ZeFoxii** [comment]
Perfect, that's exactly in line with what I was thinking. Yes! Thank you!
